"""
Unit tests for Pre/PLEXOS/UpdateHorizon/update_horizon.py

Tests the horizon update and XML regeneration workflow.
Both eecloud and plexos_sdk are mocked since they are not installed locally.
"""
import sys
from datetime import datetime
from unittest.mock import patch, MagicMock

import pytest

# ── Mock the proprietary SDKs before importing the script module ────────────
# The script imports eecloud and plexos_sdk at the top level, so we must
# inject mock modules into sys.modules before the module loader runs.

_mock_eecloud = MagicMock()
_mock_plexos_sdk = MagicMock()
sys.modules.setdefault("eecloud", _mock_eecloud)
sys.modules.setdefault("eecloud.cloudsdk", _mock_eecloud.cloudsdk)
sys.modules.setdefault("plexos_sdk", _mock_plexos_sdk)

from .conftest import get_module

MOD = get_module("update_horizon")


class TestHorizonUpdater:
    """Test the HorizonUpdater class."""

    def test_update_success(self, tmp_dir):
        """Successful horizon update and XML regeneration."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()
        (sim_dir / "reference.db").write_text("mock db")
        (sim_dir / "project.xml").write_text("mock xml")

        mock_horizon = MagicMock()
        mock_horizon.name = "Base"

        mock_sdk_instance = MagicMock()
        mock_sdk_instance.get_horizon_by_name.return_value = mock_horizon
        mock_sdk_instance.update_horizon.return_value = mock_horizon
        mock_sdk_instance.__enter__ = MagicMock(return_value=mock_sdk_instance)
        mock_sdk_instance.__exit__ = MagicMock(return_value=False)
        mock_sdk_instance.transaction.return_value.__enter__ = MagicMock()
        mock_sdk_instance.transaction.return_value.__exit__ = MagicMock(return_value=False)

        mock_response_data = MagicMock()

        with patch.object(MOD, "PLEXOSSDK", return_value=mock_sdk_instance):
            with patch.object(MOD, "CloudSDK") as MockCloudSDK:
                mock_pxc = MockCloudSDK.return_value
                mock_pxc.inputdata.convert_database_to_xml.return_value = MagicMock()
                with patch.object(MOD, "SDKBase") as MockSDKBase:
                    MockSDKBase.get_response_data.return_value = mock_response_data

                    updater = MOD.HorizonUpdater(
                        cli_path="mock_cli",
                        simulation_path=str(sim_dir),
                        study_id="study_123",
                    )
                    success = updater.update(
                        horizon_name="Base",
                        date_from=datetime(2026, 1, 1),
                        step_count=12,
                        step_type=3,
                    )

        assert success is True
        # project.xml should have been deleted (then regenerated by the mock)
        mock_sdk_instance.get_horizon_by_name.assert_called_once_with("Base")
        mock_sdk_instance.update_horizon.assert_called_once()

    def test_update_db_not_found(self, tmp_dir):
        """Returns False when reference.db does not exist."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()

        updater = MOD.HorizonUpdater(
            cli_path="mock_cli",
            simulation_path=str(sim_dir),
            study_id="study_123",
        )
        success = updater.update(horizon_name="Base", date_from=datetime(2026, 1, 1))

        assert success is False

    def test_xml_deleted_before_conversion(self, tmp_dir):
        """The existing project.xml is deleted before db-to-xml conversion."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()
        (sim_dir / "reference.db").write_text("mock db")
        xml_file = sim_dir / "project.xml"
        xml_file.write_text("old xml")

        mock_horizon = MagicMock()
        mock_horizon.name = "Base"

        mock_sdk_instance = MagicMock()
        mock_sdk_instance.get_horizon_by_name.return_value = mock_horizon
        mock_sdk_instance.update_horizon.return_value = MagicMock()
        mock_sdk_instance.__enter__ = MagicMock(return_value=mock_sdk_instance)
        mock_sdk_instance.__exit__ = MagicMock(return_value=False)
        mock_sdk_instance.transaction.return_value.__enter__ = MagicMock()
        mock_sdk_instance.transaction.return_value.__exit__ = MagicMock(return_value=False)

        with patch.object(MOD, "PLEXOSSDK", return_value=mock_sdk_instance):
            with patch.object(MOD, "CloudSDK") as MockCloudSDK:
                mock_pxc = MockCloudSDK.return_value
                mock_pxc.inputdata.convert_database_to_xml.return_value = MagicMock()
                with patch.object(MOD, "SDKBase") as MockSDKBase:
                    MockSDKBase.get_response_data.return_value = MagicMock()

                    updater = MOD.HorizonUpdater(
                        cli_path="mock_cli",
                        simulation_path=str(sim_dir),
                        study_id="study_123",
                    )
                    updater.update(horizon_name="Base", step_count=24)

        # XML file should have been deleted (the mock doesn't recreate it)
        assert not xml_file.exists()

    def test_convert_db_to_xml_called_with_correct_params(self, tmp_dir):
        """The Cloud CLI converter is called with correct parameter names."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()
        (sim_dir / "reference.db").write_text("mock db")

        mock_horizon = MagicMock()
        mock_horizon.name = "Base"

        mock_sdk_instance = MagicMock()
        mock_sdk_instance.get_horizon_by_name.return_value = mock_horizon
        mock_sdk_instance.update_horizon.return_value = MagicMock()
        mock_sdk_instance.__enter__ = MagicMock(return_value=mock_sdk_instance)
        mock_sdk_instance.__exit__ = MagicMock(return_value=False)
        mock_sdk_instance.transaction.return_value.__enter__ = MagicMock()
        mock_sdk_instance.transaction.return_value.__exit__ = MagicMock(return_value=False)

        with patch.object(MOD, "PLEXOSSDK", return_value=mock_sdk_instance):
            with patch.object(MOD, "CloudSDK") as MockCloudSDK:
                mock_pxc = MockCloudSDK.return_value
                mock_pxc.inputdata.convert_database_to_xml.return_value = MagicMock()
                with patch.object(MOD, "SDKBase") as MockSDKBase:
                    MockSDKBase.get_response_data.return_value = MagicMock()

                    updater = MOD.HorizonUpdater(
                        cli_path="mock_cli",
                        simulation_path=str(sim_dir),
                        study_id="study_123",
                    )
                    updater.update(horizon_name="Base", date_from=datetime(2026, 1, 1))

        call_kwargs = mock_pxc.inputdata.convert_database_to_xml.call_args.kwargs
        assert "db_file_path" in call_kwargs
        assert "xml_file_path" in call_kwargs
        assert "study_id" in call_kwargs
        assert call_kwargs["study_id"] == "study_123"
        assert call_kwargs["print_message"] is False

    def test_update_horizon_called_with_correct_params(self, tmp_dir):
        """PLEXOS SDK update_horizon receives the correct arguments."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()
        (sim_dir / "reference.db").write_text("mock db")

        mock_horizon = MagicMock()
        mock_horizon.name = "Base"

        mock_sdk_instance = MagicMock()
        mock_sdk_instance.get_horizon_by_name.return_value = mock_horizon
        mock_sdk_instance.update_horizon.return_value = mock_horizon
        mock_sdk_instance.__enter__ = MagicMock(return_value=mock_sdk_instance)
        mock_sdk_instance.__exit__ = MagicMock(return_value=False)
        mock_sdk_instance.transaction.return_value.__enter__ = MagicMock()
        mock_sdk_instance.transaction.return_value.__exit__ = MagicMock(return_value=False)

        with patch.object(MOD, "PLEXOSSDK", return_value=mock_sdk_instance):
            with patch.object(MOD, "CloudSDK") as MockCloudSDK:
                mock_pxc = MockCloudSDK.return_value
                mock_pxc.inputdata.convert_database_to_xml.return_value = MagicMock()
                with patch.object(MOD, "SDKBase") as MockSDKBase:
                    MockSDKBase.get_response_data.return_value = MagicMock()

                    updater = MOD.HorizonUpdater(
                        cli_path="mock_cli",
                        simulation_path=str(sim_dir),
                        study_id="study_123",
                    )
                    updater.update(
                        horizon_name="Base",
                        date_from=datetime(2026, 6, 15),
                        step_count=24,
                        step_type=3,
                    )

        assert mock_sdk_instance.update_horizon.call_args.args[0] is mock_horizon
        call_kwargs = mock_sdk_instance.update_horizon.call_args.kwargs
        assert call_kwargs["date_from"] == datetime(2026, 6, 15)
        assert call_kwargs["step_count"] == 24
        assert call_kwargs["step_type"] == 3
        assert call_kwargs["chrono_date_from"] == datetime(2026, 6, 15)

    def test_update_horizon_returns_none(self, tmp_dir):
        """Returns False when sdk.update_horizon() returns None."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()
        (sim_dir / "reference.db").write_text("mock db")

        mock_horizon = MagicMock()
        mock_horizon.name = "Base"

        mock_sdk_instance = MagicMock()
        mock_sdk_instance.get_horizon_by_name.return_value = mock_horizon
        mock_sdk_instance.update_horizon.return_value = None
        mock_sdk_instance.__enter__ = MagicMock(return_value=mock_sdk_instance)
        mock_sdk_instance.__exit__ = MagicMock(return_value=False)
        mock_sdk_instance.transaction.return_value.__enter__ = MagicMock()
        mock_sdk_instance.transaction.return_value.__exit__ = MagicMock(return_value=False)

        with patch.object(MOD, "PLEXOSSDK", return_value=mock_sdk_instance):
            updater = MOD.HorizonUpdater(
                cli_path="mock_cli",
                simulation_path=str(sim_dir),
                study_id="study_123",
            )
            success = updater.update(horizon_name="Base", step_count=12)

        assert success is False

    def test_conversion_failure_returns_false(self, tmp_dir):
        """Returns False when db-to-xml conversion fails."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()
        (sim_dir / "reference.db").write_text("mock db")

        mock_horizon = MagicMock()
        mock_horizon.name = "Base"

        mock_sdk_instance = MagicMock()
        mock_sdk_instance.get_horizon_by_name.return_value = mock_horizon
        mock_sdk_instance.update_horizon.return_value = MagicMock()
        mock_sdk_instance.__enter__ = MagicMock(return_value=mock_sdk_instance)
        mock_sdk_instance.__exit__ = MagicMock(return_value=False)
        mock_sdk_instance.transaction.return_value.__enter__ = MagicMock()
        mock_sdk_instance.transaction.return_value.__exit__ = MagicMock(return_value=False)

        mock_response = MagicMock()
        mock_response.Message = "Conversion error"

        with patch.object(MOD, "PLEXOSSDK", return_value=mock_sdk_instance):
            with patch.object(MOD, "CloudSDK") as MockCloudSDK:
                mock_pxc = MockCloudSDK.return_value
                mock_pxc.inputdata.convert_database_to_xml.return_value = mock_response
                with patch.object(MOD, "SDKBase") as MockSDKBase:
                    MockSDKBase.get_response_data.return_value = None

                    updater = MOD.HorizonUpdater(
                        cli_path="mock_cli",
                        simulation_path=str(sim_dir),
                        study_id="study_123",
                    )
                    success = updater.update(horizon_name="Base", step_count=12)

        assert success is False


class TestMainFunction:
    """Test the main function with argument parsing."""

    def test_main_missing_required_args(self):
        """Main fails when --horizon-name is missing."""
        with patch("sys.argv", ["update_horizon.py"]):
            with pytest.raises(SystemExit) as exc:
                MOD.main()
            assert exc.value.code == 2

    def test_main_no_update_args(self, tmp_dir):
        """Main returns 1 when no update arguments are provided."""
        with patch("sys.argv", ["update_horizon.py", "--horizon-name", "Base"]):
            exit_code = MOD.main()

        assert exit_code == 1

    def test_main_with_valid_args(self, tmp_dir):
        """Main returns 0 on successful update."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()
        (sim_dir / "reference.db").write_text("mock db")

        mock_horizon = MagicMock()
        mock_horizon.name = "Base"

        mock_sdk_instance = MagicMock()
        mock_sdk_instance.get_horizon_by_name.return_value = mock_horizon
        mock_sdk_instance.update_horizon.return_value = MagicMock()
        mock_sdk_instance.__enter__ = MagicMock(return_value=mock_sdk_instance)
        mock_sdk_instance.__exit__ = MagicMock(return_value=False)
        mock_sdk_instance.transaction.return_value.__enter__ = MagicMock()
        mock_sdk_instance.transaction.return_value.__exit__ = MagicMock(return_value=False)

        with patch("sys.argv", [
            "update_horizon.py",
            "--horizon-name", "Base",
            "--date-from", "2026-01-01",
            "--step-count", "12",
            "--step-type", "month",
        ]):
            with patch.object(MOD, "SIMULATION_PATH", str(sim_dir)), \
                 patch.object(MOD, "PLEXOSSDK", return_value=mock_sdk_instance), \
                 patch.object(MOD, "CloudSDK") as MockCloudSDK, \
                 patch.object(MOD, "SDKBase") as MockSDKBase:
                MockCloudSDK.return_value.inputdata.convert_database_to_xml.return_value = MagicMock()
                MockSDKBase.get_response_data.return_value = MagicMock()
                exit_code = MOD.main()

        assert exit_code == 0

    def test_main_step_type_name_to_int(self, tmp_dir):
        """Step type names (day/week/month/year) are converted to integers."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()
        (sim_dir / "reference.db").write_text("mock db")

        mock_horizon = MagicMock()
        mock_horizon.name = "H"

        mock_sdk_instance = MagicMock()
        mock_sdk_instance.get_horizon_by_name.return_value = mock_horizon
        mock_sdk_instance.update_horizon.return_value = MagicMock()
        mock_sdk_instance.__enter__ = MagicMock(return_value=mock_sdk_instance)
        mock_sdk_instance.__exit__ = MagicMock(return_value=False)
        mock_sdk_instance.transaction.return_value.__enter__ = MagicMock()
        mock_sdk_instance.transaction.return_value.__exit__ = MagicMock(return_value=False)

        with patch("sys.argv", [
            "update_horizon.py",
            "--horizon-name", "H",
            "--step-type", "week",
            "--step-count", "52",
        ]):
            with patch.object(MOD, "SIMULATION_PATH", str(sim_dir)), \
                 patch.object(MOD, "PLEXOSSDK", return_value=mock_sdk_instance), \
                 patch.object(MOD, "CloudSDK") as MockCloudSDK, \
                 patch.object(MOD, "SDKBase") as MockSDKBase:
                MockCloudSDK.return_value.inputdata.convert_database_to_xml.return_value = MagicMock()
                MockSDKBase.get_response_data.return_value = MagicMock()
                exit_code = MOD.main()

        assert exit_code == 0
        call_kwargs = mock_sdk_instance.update_horizon.call_args.kwargs
        assert call_kwargs["step_type"] == 2  # week = 2

    def test_main_url_encoded_horizon_name_decoded(self, tmp_dir):
        """URL-encoded %20 in --horizon-name is decoded to a space before calling the SDK."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()
        (sim_dir / "reference.db").write_text("mock db")

        mock_horizon = MagicMock()
        mock_horizon.name = "Base Horizon"

        mock_sdk_instance = MagicMock()
        mock_sdk_instance.get_horizon_by_name.return_value = mock_horizon
        mock_sdk_instance.update_horizon.return_value = MagicMock()
        mock_sdk_instance.__enter__ = MagicMock(return_value=mock_sdk_instance)
        mock_sdk_instance.__exit__ = MagicMock(return_value=False)
        mock_sdk_instance.transaction.return_value.__enter__ = MagicMock()
        mock_sdk_instance.transaction.return_value.__exit__ = MagicMock(return_value=False)

        with patch("sys.argv", [
            "update_horizon.py",
            "--horizon-name", "Base%20Horizon",
            "--step-count", "12",
        ]):
            with patch.object(MOD, "SIMULATION_PATH", str(sim_dir)), \
                 patch.object(MOD, "PLEXOSSDK", return_value=mock_sdk_instance), \
                 patch.object(MOD, "CloudSDK") as MockCloudSDK, \
                 patch.object(MOD, "SDKBase") as MockSDKBase:
                MockCloudSDK.return_value.inputdata.convert_database_to_xml.return_value = MagicMock()
                MockSDKBase.get_response_data.return_value = MagicMock()
                exit_code = MOD.main()

        assert exit_code == 0
        mock_sdk_instance.get_horizon_by_name.assert_called_once_with("Base Horizon")

    def test_main_quoted_horizon_name_stripped(self, tmp_dir):
        """Surrounding quotes around --horizon-name are stripped before calling the SDK."""
        sim_dir = tmp_dir / "simulation"
        sim_dir.mkdir()
        (sim_dir / "reference.db").write_text("mock db")

        mock_horizon = MagicMock()
        mock_horizon.name = "Base"

        mock_sdk_instance = MagicMock()
        mock_sdk_instance.get_horizon_by_name.return_value = mock_horizon
        mock_sdk_instance.update_horizon.return_value = MagicMock()
        mock_sdk_instance.__enter__ = MagicMock(return_value=mock_sdk_instance)
        mock_sdk_instance.__exit__ = MagicMock(return_value=False)
        mock_sdk_instance.transaction.return_value.__enter__ = MagicMock()
        mock_sdk_instance.transaction.return_value.__exit__ = MagicMock(return_value=False)

        with patch("sys.argv", [
            "update_horizon.py",
            "--horizon-name", "'Base'",
            "--step-count", "12",
        ]):
            with patch.object(MOD, "SIMULATION_PATH", str(sim_dir)), \
                 patch.object(MOD, "PLEXOSSDK", return_value=mock_sdk_instance), \
                 patch.object(MOD, "CloudSDK") as MockCloudSDK, \
                 patch.object(MOD, "SDKBase") as MockSDKBase:
                MockCloudSDK.return_value.inputdata.convert_database_to_xml.return_value = MagicMock()
                MockSDKBase.get_response_data.return_value = MagicMock()
                exit_code = MOD.main()

        assert exit_code == 0
        mock_sdk_instance.get_horizon_by_name.assert_called_once_with("Base")
